
import os
import sqlite3
from contextlib import contextmanager
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent / "data"
DB_PATH = DATA_DIR / "gst_billing.db"
UPLOAD_DIR = DATA_DIR / "uploads"
INVOICE_DIR = DATA_DIR / "invoices"

for p in (DATA_DIR, UPLOAD_DIR, INVOICE_DIR):
    p.mkdir(parents=True, exist_ok=True)


def _get_database_url():
    value = os.getenv("DATABASE_URL", "").strip()
    if value:
        return value
    try:
        import streamlit as st
        return str(st.secrets.get("DATABASE_URL", "")).strip()
    except Exception:
        return ""


def database_backend():
    return "postgresql" if _get_database_url() else "sqlite"


class _DBConnection:
    def __init__(self):
        self.backend = database_backend()
        if self.backend == "postgresql":
            import psycopg2
            from psycopg2.extras import RealDictCursor
            self.conn = psycopg2.connect(_get_database_url())
            self.conn.autocommit = False
            self.cursor_factory = RealDictCursor
        else:
            self.conn = sqlite3.connect(DB_PATH)
            self.conn.row_factory = sqlite3.Row
            self.conn.execute("PRAGMA foreign_keys = ON")

    def execute(self, sql, params=()):
        if self.backend == "postgresql":
            cur = self.conn.cursor(cursor_factory=self.cursor_factory)
            cur.execute(sql.replace("?", "%s"), params)
            return cur
        return self.conn.execute(sql, params)

    def executemany(self, sql, seq):
        if self.backend == "postgresql":
            cur = self.conn.cursor(cursor_factory=self.cursor_factory)
            cur.executemany(sql.replace("?", "%s"), seq)
            return cur
        return self.conn.executemany(sql, seq)

    def executescript(self, sql):
        if self.backend == "postgresql":
            cur = self.conn.cursor(cursor_factory=self.cursor_factory)
            for statement in sql.split(";"):
                statement = statement.strip()
                if statement:
                    cur.execute(statement)
            return cur
        return self.conn.executescript(sql)

    def commit(self):
        self.conn.commit()

    def rollback(self):
        self.conn.rollback()

    def close(self):
        self.conn.close()


@contextmanager
def get_connection():
    db = _DBConnection()
    try:
        yield db
        db.commit()
    except Exception:
        db.rollback()
        raise
    finally:
        db.close()


def _active_business_id():
    try:
        import streamlit as st
        value = st.session_state.get("active_business_id")
        if value:
            return int(value)
    except Exception:
        pass
    return 1


def get_active_business_id():
    return _active_business_id()


def set_active_business_id(business_id):
    business_id = int(business_id)
    with get_connection() as conn:
        row = conn.execute("SELECT id FROM businesses WHERE id=? AND active=1", (business_id,)).fetchone()
        if not row:
            raise ValueError("Business is not available.")
    try:
        import streamlit as st
        st.session_state.active_business_id = business_id
    except Exception:
        pass
    return business_id


def _ensure_column(conn, table, column, definition):
    if conn.backend == "postgresql":
        cols = {r["column_name"] for r in conn.execute(
            "SELECT column_name FROM information_schema.columns WHERE table_name=?", (table,)
        ).fetchall()}
    else:
        cols = {r["name"] for r in conn.execute(f"PRAGMA table_info({table})").fetchall()}
    if column not in cols:
        conn.execute(f"ALTER TABLE {table} ADD COLUMN {column} {definition}")


def _business_columns(conn):
    if conn.backend == "postgresql":
        return {r["column_name"] for r in conn.execute(
            "SELECT column_name FROM information_schema.columns WHERE table_name='businesses'"
        ).fetchall()}
    return {r["name"] for r in conn.execute("PRAGMA table_info(businesses)").fetchall()}


def _ensure_businesses(conn):
    id_definition = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if conn.backend == "postgresql" else "INTEGER PRIMARY KEY AUTOINCREMENT"
    conn.execute(f"""
        CREATE TABLE IF NOT EXISTS businesses (
            id {id_definition},
            business_name TEXT NOT NULL DEFAULT '',
            gstin TEXT NOT NULL DEFAULT '',
            address TEXT NOT NULL DEFAULT '',
            state TEXT NOT NULL DEFAULT '',
            state_code TEXT NOT NULL DEFAULT '',
            account_no TEXT NOT NULL DEFAULT '',
            ifsc TEXT NOT NULL DEFAULT '',
            branch TEXT NOT NULL DEFAULT '',
            logo_path TEXT NOT NULL DEFAULT '',
            invoice_prefix TEXT NOT NULL DEFAULT 'INV',
            invoice_separator TEXT NOT NULL DEFAULT '/',
            invoice_digits INTEGER NOT NULL DEFAULT 3,
            default_state TEXT NOT NULL DEFAULT 'Maharashtra',
            default_state_code TEXT NOT NULL DEFAULT '27',
            default_unit TEXT NOT NULL DEFAULT 'NOS',
            default_gst_rate DOUBLE PRECISION NOT NULL DEFAULT 18,
            default_invoice_notes TEXT NOT NULL DEFAULT '',
            default_report_period TEXT NOT NULL DEFAULT 'Current Month',
            invoice_sequence_start INTEGER NOT NULL DEFAULT 1,
            active INTEGER NOT NULL DEFAULT 1,
            created_by_user_id INTEGER,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)


def _ensure_tenant_columns(conn):
    _ensure_column(conn, "businesses", "created_by_user_id", "INTEGER")
    for table in ("clients", "invoices", "item_master"):
        definition = "INTEGER NOT NULL DEFAULT 1"
        _ensure_column(conn, table, "business_id", definition)


def _ensure_access_table(conn):
    conn.execute("""
        CREATE TABLE IF NOT EXISTS user_business_access (
            user_id INTEGER NOT NULL,
            business_id INTEGER NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY(user_id, business_id),
            FOREIGN KEY(user_id) REFERENCES app_users(id) ON DELETE CASCADE,
            FOREIGN KEY(business_id) REFERENCES businesses(id) ON DELETE CASCADE
        )
    """)
    conn.execute("CREATE INDEX IF NOT EXISTS idx_uba_user ON user_business_access(user_id)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_uba_business ON user_business_access(business_id)")


def _ensure_application_settings(conn):
    conn.execute("""
        CREATE TABLE IF NOT EXISTS application_settings (
            setting_key TEXT PRIMARY KEY,
            setting_value TEXT NOT NULL DEFAULT '',
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    if conn.backend == "postgresql":
        conn.execute(
            "INSERT INTO application_settings(setting_key,setting_value) VALUES(?,?) ON CONFLICT(setting_key) DO NOTHING",
            ("allow_user_business_creation", "0")
        )
    else:
        conn.execute(
            "INSERT OR IGNORE INTO application_settings(setting_key,setting_value) VALUES(?,?)",
            ("allow_user_business_creation", "0")
        )


def get_application_setting(key, default=""):
    with get_connection() as conn:
        row = conn.execute(
            "SELECT setting_value FROM application_settings WHERE setting_key=?", (key,)
        ).fetchone()
        return row["setting_value"] if row else default


def set_application_setting(key, value):
    with get_connection() as conn:
        if conn.backend == "postgresql":
            conn.execute(
                "INSERT INTO application_settings(setting_key,setting_value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) "
                "ON CONFLICT(setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value, updated_at=CURRENT_TIMESTAMP",
                (key, str(value))
            )
        else:
            conn.execute(
                "INSERT OR REPLACE INTO application_settings(setting_key,setting_value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP)",
                (key, str(value))
            )


def allow_user_business_creation():
    return get_application_setting("allow_user_business_creation", "0") == "1"


def init_db():
    with get_connection() as conn:
        # Keep the original schema for backward compatibility.
        conn.executescript("""
        CREATE TABLE IF NOT EXISTS business_profile (
            id INTEGER PRIMARY KEY CHECK (id = 1),
            business_name TEXT NOT NULL DEFAULT '',
            gstin TEXT NOT NULL DEFAULT '',
            address TEXT NOT NULL DEFAULT '',
            state TEXT NOT NULL DEFAULT '',
            state_code TEXT NOT NULL DEFAULT '',
            account_no TEXT NOT NULL DEFAULT '',
            ifsc TEXT NOT NULL DEFAULT '',
            branch TEXT NOT NULL DEFAULT '',
            logo_path TEXT NOT NULL DEFAULT '',
            invoice_prefix TEXT NOT NULL DEFAULT 'INV',
            invoice_separator TEXT NOT NULL DEFAULT '/',
            invoice_digits INTEGER NOT NULL DEFAULT 3,
            default_state TEXT NOT NULL DEFAULT 'Maharashtra',
            default_state_code TEXT NOT NULL DEFAULT '27',
            default_unit TEXT NOT NULL DEFAULT 'NOS',
            default_gst_rate DOUBLE PRECISION NOT NULL DEFAULT 18,
            default_invoice_notes TEXT NOT NULL DEFAULT '',
            default_report_period TEXT NOT NULL DEFAULT 'Current Month',
            invoice_sequence_start INTEGER NOT NULL DEFAULT 1
        );
        CREATE TABLE IF NOT EXISTS clients (
            id INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            gstin TEXT NOT NULL DEFAULT '',
            address TEXT NOT NULL DEFAULT '',
            state TEXT NOT NULL,
            state_code TEXT NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS invoices (
            id INTEGER PRIMARY KEY,
            invoice_no TEXT NOT NULL,
            invoice_date TEXT NOT NULL,
            client_id INTEGER NOT NULL,
            place_of_supply_state TEXT NOT NULL,
            place_of_supply_code TEXT NOT NULL,
            tax_type TEXT NOT NULL,
            subtotal DOUBLE PRECISION NOT NULL DEFAULT 0,
            discount_total DOUBLE PRECISION NOT NULL DEFAULT 0,
            taxable_total DOUBLE PRECISION NOT NULL DEFAULT 0,
            cgst_total DOUBLE PRECISION NOT NULL DEFAULT 0,
            sgst_total DOUBLE PRECISION NOT NULL DEFAULT 0,
            igst_total DOUBLE PRECISION NOT NULL DEFAULT 0,
            grand_total DOUBLE PRECISION NOT NULL DEFAULT 0,
            amount_in_words TEXT NOT NULL DEFAULT '',
            notes TEXT NOT NULL DEFAULT '',
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS invoice_items (
            id INTEGER PRIMARY KEY,
            invoice_id INTEGER NOT NULL,
            description TEXT NOT NULL,
            hsn_sac TEXT NOT NULL DEFAULT '',
            quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
            unit TEXT NOT NULL DEFAULT 'NOS',
            rate DOUBLE PRECISION NOT NULL DEFAULT 0,
            discount_percent DOUBLE PRECISION NOT NULL DEFAULT 0,
            gross_value DOUBLE PRECISION NOT NULL DEFAULT 0,
            discount_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
            taxable_value DOUBLE PRECISION NOT NULL DEFAULT 0,
            gst_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
            cgst_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
            sgst_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
            igst_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
            cgst_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
            sgst_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
            igst_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
            line_total DOUBLE PRECISION NOT NULL DEFAULT 0
        );
        CREATE TABLE IF NOT EXISTS item_master (
            id INTEGER PRIMARY KEY,
            description TEXT NOT NULL,
            hsn_sac TEXT NOT NULL DEFAULT '',
            unit TEXT NOT NULL DEFAULT 'NOS',
            default_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
            gst_rate DOUBLE PRECISION NOT NULL DEFAULT 18,
            active INTEGER NOT NULL DEFAULT 1,
            created_by_user_id INTEGER,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS app_users (
            id INTEGER PRIMARY KEY,
            username TEXT NOT NULL,
            password_hash TEXT NOT NULL,
            role TEXT NOT NULL DEFAULT 'Admin',
            active INTEGER NOT NULL DEFAULT 1,
            created_by_user_id INTEGER,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            failed_login_count INTEGER NOT NULL DEFAULT 0,
            locked_until TEXT NOT NULL DEFAULT '',
            last_login_at TEXT NOT NULL DEFAULT ''
        );
        """)

        # Add columns introduced in previous releases.
        for col, definition in {
            "default_state": "TEXT NOT NULL DEFAULT 'Maharashtra'",
            "default_state_code": "TEXT NOT NULL DEFAULT '27'",
            "default_unit": "TEXT NOT NULL DEFAULT 'NOS'",
            "default_gst_rate": "DOUBLE PRECISION NOT NULL DEFAULT 18",
            "default_invoice_notes": "TEXT NOT NULL DEFAULT ''",
            "default_report_period": "TEXT NOT NULL DEFAULT 'Current Month'",
            "invoice_sequence_start": "INTEGER NOT NULL DEFAULT 1",
        }.items():
            _ensure_column(conn, "business_profile", col, definition)

        for col, definition in {
            "failed_login_count": "INTEGER NOT NULL DEFAULT 0",
            "locked_until": "TEXT NOT NULL DEFAULT ''",
            "last_login_at": "TEXT NOT NULL DEFAULT ''",
        }.items():
            _ensure_column(conn, "app_users", col, definition)

        _ensure_businesses(conn)

        # Create the first business from the existing singleton profile.
        old = conn.execute("SELECT * FROM business_profile WHERE id=1").fetchone()
        existing_business = conn.execute("SELECT id FROM businesses WHERE id=1").fetchone()
        if not existing_business:
            if old:
                cols = [
                    "business_name","gstin","address","state","state_code","account_no","ifsc","branch",
                    "logo_path","invoice_prefix","invoice_separator","invoice_digits","default_state",
                    "default_state_code","default_unit","default_gst_rate","default_invoice_notes",
                    "default_report_period","invoice_sequence_start"
                ]
                values = [old[c] for c in cols]
                conn.execute(
                    f"""INSERT INTO businesses(id,{','.join(cols)}) VALUES(1,{','.join('?' for _ in cols)})""",
                    tuple(values)
                )
            else:
                conn.execute("INSERT INTO businesses(id) VALUES(1)")

        _ensure_tenant_columns(conn)
        _ensure_access_table(conn)
        _ensure_application_settings(conn)

        # v1.2 freeze features: business lifecycle, invoice status/payment, item codes and audit log.
        _ensure_column(conn, "businesses", "archived_at", "TEXT NOT NULL DEFAULT ''")
        _ensure_column(conn, "invoices", "status", "TEXT NOT NULL DEFAULT 'ACTIVE'")
        _ensure_column(conn, "invoices", "cancellation_reason", "TEXT NOT NULL DEFAULT ''")
        _ensure_column(conn, "invoices", "cancelled_at", "TEXT NOT NULL DEFAULT ''")
        _ensure_column(conn, "invoices", "cancelled_by_user_id", "INTEGER")
        _ensure_column(conn, "invoices", "payment_status", "TEXT NOT NULL DEFAULT 'Unpaid'")
        _ensure_column(conn, "invoices", "amount_received", "DOUBLE PRECISION NOT NULL DEFAULT 0")
        _ensure_column(conn, "invoices", "balance_due", "DOUBLE PRECISION NOT NULL DEFAULT 0")
        _ensure_column(conn, "item_master", "item_code", "TEXT NOT NULL DEFAULT ''")
        audit_id_definition = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if conn.backend == "postgresql" else "INTEGER PRIMARY KEY AUTOINCREMENT"
        conn.execute(f"""CREATE TABLE IF NOT EXISTS audit_logs (
            id {audit_id_definition}, user_id INTEGER, business_id INTEGER,
            action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id INTEGER,
            reference TEXT NOT NULL DEFAULT '', details TEXT NOT NULL DEFAULT '',
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )""")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_audit_business ON audit_logs(business_id, created_at DESC)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_audit_user ON audit_logs(user_id, created_at DESC)")
        conn.execute("UPDATE invoices SET status='ACTIVE' WHERE status IS NULL OR status=''")
        conn.execute("UPDATE invoices SET payment_status='Unpaid' WHERE payment_status IS NULL OR payment_status=''")
        conn.execute("UPDATE invoices SET amount_received=0 WHERE amount_received IS NULL")
        conn.execute("UPDATE invoices SET balance_due=grand_total-amount_received WHERE balance_due IS NULL")
        for brow in conn.execute("SELECT id FROM businesses ORDER BY id").fetchall():
            bid = brow["id"]
            missing = conn.execute("SELECT id FROM item_master WHERE business_id=? AND (item_code IS NULL OR item_code='') ORDER BY id", (bid,)).fetchall()
            for idx, row in enumerate(missing, 1):
                conn.execute("UPDATE item_master SET item_code=? WHERE id=? AND business_id=?", (f"ITM{idx:03d}", row["id"], bid))
        if conn.backend == "postgresql":
            conn.execute("CREATE UNIQUE INDEX IF NOT EXISTS uq_item_business_code ON item_master(business_id, item_code) WHERE item_code <> ''")

        if conn.backend == "postgresql":
            conn.execute("""
                SELECT setval(
                    pg_get_serial_sequence('businesses','id'),
                    COALESCE(MAX(id),1),
                    MAX(id) IS NOT NULL
                )
                FROM businesses
            """)

        # Existing records belong to the original business.
        conn.execute("UPDATE clients SET business_id=1 WHERE business_id IS NULL")
        conn.execute("UPDATE invoices SET business_id=1 WHERE business_id IS NULL")
        conn.execute("UPDATE item_master SET business_id=1 WHERE business_id IS NULL")

        # Give every existing user access to the original business.
        users = conn.execute("SELECT id FROM app_users").fetchall()
        for user in users:
            conn.execute(
                "INSERT INTO user_business_access(user_id,business_id) VALUES(?,1) ON CONFLICT DO NOTHING"
                if conn.backend == "postgresql"
                else "INSERT OR IGNORE INTO user_business_access(user_id,business_id) VALUES(?,1)",
                (user["id"],)
            )

        # PostgreSQL: remove the old global invoice uniqueness so each business
        # can independently use the same invoice series.
        if conn.backend == "postgresql":
            conn.execute("ALTER TABLE invoices DROP CONSTRAINT IF EXISTS invoices_invoice_no_key")
            conn.execute("CREATE UNIQUE INDEX IF NOT EXISTS uq_invoice_business_no ON invoices(business_id, invoice_no)")
            conn.execute("ALTER TABLE item_master DROP CONSTRAINT IF EXISTS item_master_description_key")
            conn.execute("CREATE UNIQUE INDEX IF NOT EXISTS uq_item_business_description ON item_master(business_id, LOWER(description))")
            conn.execute("CREATE INDEX IF NOT EXISTS idx_clients_business ON clients(business_id)")
            conn.execute("CREATE INDEX IF NOT EXISTS idx_invoices_business ON invoices(business_id)")
            conn.execute("CREATE INDEX IF NOT EXISTS idx_items_business ON item_master(business_id)")
        else:
            conn.execute("CREATE INDEX IF NOT EXISTS idx_clients_business ON clients(business_id)")
            conn.execute("CREATE INDEX IF NOT EXISTS idx_invoices_business ON invoices(business_id)")
            conn.execute("CREATE INDEX IF NOT EXISTS idx_items_business ON item_master(business_id)")


def row_to_dict(row):
    return dict(row) if row else None


def _current_user_id():
    try:
        import streamlit as st
        return (st.session_state.get("authenticated_user") or {}).get("id")
    except Exception:
        return None


def log_audit(action, entity_type, entity_id=None, reference="", details="", user_id=None, business_id=None):
    uid = user_id if user_id is not None else _current_user_id()
    bid = business_id if business_id is not None else _active_business_id()
    with get_connection() as conn:
        conn.execute("""INSERT INTO audit_logs(user_id,business_id,action,entity_type,entity_id,reference,details)
                       VALUES(?,?,?,?,?,?,?)""", (uid,bid,action,entity_type,entity_id,reference or "",details or ""))


def list_audit_logs(limit=300, business_id=None):
    with get_connection() as conn:
        if business_id:
            rows=conn.execute("""SELECT a.*,COALESCE(u.username,'System') username,COALESCE(b.business_name,'') business_name
                                FROM audit_logs a LEFT JOIN app_users u ON u.id=a.user_id
                                LEFT JOIN businesses b ON b.id=a.business_id
                                WHERE a.business_id=? ORDER BY a.created_at DESC,a.id DESC LIMIT ?""", (business_id,int(limit))).fetchall()
        else:
            rows=conn.execute("""SELECT a.*,COALESCE(u.username,'System') username,COALESCE(b.business_name,'') business_name
                                FROM audit_logs a LEFT JOIN app_users u ON u.id=a.user_id
                                LEFT JOIN businesses b ON b.id=a.business_id
                                ORDER BY a.created_at DESC,a.id DESC LIMIT ?""", (int(limit),)).fetchall()
        return [dict(r) for r in rows]


def list_all_businesses():
    with get_connection() as conn:
        return [dict(r) for r in conn.execute("SELECT * FROM businesses ORDER BY active DESC,business_name COLLATE NOCASE").fetchall()]


def archive_business(business_id):
    bid=int(business_id)
    with get_connection() as conn:
        row=conn.execute("SELECT business_name,active FROM businesses WHERE id=?",(bid,)).fetchone()
        if not row: raise ValueError("Business not found.")
        if not row["active"]: raise ValueError("Business is already archived.")
        if conn.execute("SELECT COUNT(*) c FROM businesses WHERE active=1").fetchone()["c"] <= 1:
            raise ValueError("The last active Business cannot be archived.")
        conn.execute("UPDATE businesses SET active=0,archived_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?",(bid,))
        name=row["business_name"]
    log_audit("ARCHIVE","BUSINESS",bid,name,"Business archived",business_id=bid)
    return name


def restore_business(business_id):
    bid=int(business_id)
    with get_connection() as conn:
        row=conn.execute("SELECT business_name FROM businesses WHERE id=?",(bid,)).fetchone()
        if not row: raise ValueError("Business not found.")
        conn.execute("UPDATE businesses SET active=1,archived_at='',updated_at=CURRENT_TIMESTAMP WHERE id=?",(bid,))
        name=row["business_name"]
    log_audit("RESTORE","BUSINESS",bid,name,"Business restored",business_id=bid)
    return name


def list_businesses_for_user(user_id, role="User"):
    with get_connection() as conn:
        if str(role).lower() == "admin":
            rows = conn.execute("SELECT * FROM businesses WHERE active=1 ORDER BY business_name COLLATE NOCASE").fetchall()
        else:
            rows = conn.execute("""
                SELECT b.*
                FROM businesses b
                JOIN user_business_access uba ON uba.business_id=b.id
                WHERE uba.user_id=? AND b.active=1
                ORDER BY b.business_name COLLATE NOCASE
            """, (user_id,)).fetchall()
        return [dict(r) for r in rows]


def create_business(data):
    with get_connection() as conn:
        cur = conn.execute("""
            INSERT INTO businesses(
                business_name,gstin,address,state,state_code,account_no,ifsc,branch,logo_path,
                invoice_prefix,invoice_separator,invoice_digits,default_state,default_state_code,
                default_unit,default_gst_rate,default_invoice_notes,default_report_period,
                invoice_sequence_start,active,created_by_user_id
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,?)
            RETURNING id
        """, (
            data.get("business_name",""), data.get("gstin",""), data.get("address",""),
            data.get("state",""), data.get("state_code",""), data.get("account_no",""),
            data.get("ifsc",""), data.get("branch",""), data.get("logo_path",""),
            data.get("invoice_prefix","INV"), data.get("invoice_separator","/"),
            data.get("invoice_digits",3), data.get("default_state","Maharashtra"),
            data.get("default_state_code","27"), data.get("default_unit","NOS"),
            data.get("default_gst_rate",18), data.get("default_invoice_notes",""),
            data.get("default_report_period","Current Month"),
            data.get("invoice_sequence_start",1), data.get("created_by_user_id")
        ))
        business_id = cur.fetchone()["id"]
    log_audit("CREATE","BUSINESS",business_id,data.get("business_name",""),"Business created",user_id=data.get("created_by_user_id"),business_id=business_id)
    return business_id


def get_business():
    business_id = _active_business_id()
    with get_connection() as conn:
        row = conn.execute("SELECT * FROM businesses WHERE id=? AND active=1", (business_id,)).fetchone()
        return row_to_dict(row)


def save_business(data):
    business_id = _active_business_id()
    with get_connection() as conn:
        conn.execute("""
        UPDATE businesses SET
            business_name=?, gstin=?, address=?, state=?, state_code=?,
            account_no=?, ifsc=?, branch=?, logo_path=?,
            invoice_prefix=?, invoice_separator=?, invoice_digits=?,
            default_state=?, default_state_code=?, default_unit=?,
            default_gst_rate=?, default_invoice_notes=?, default_report_period=?,
            invoice_sequence_start=?, updated_at=CURRENT_TIMESTAMP
        WHERE id=?
        """, (
            data["business_name"], data["gstin"], data["address"], data["state"],
            data["state_code"], data["account_no"], data["ifsc"], data["branch"],
            data["logo_path"], data["invoice_prefix"], data["invoice_separator"],
            data["invoice_digits"], data["default_state"], data["default_state_code"],
            data["default_unit"], data["default_gst_rate"],
            data["default_invoice_notes"], data["default_report_period"],
            data["invoice_sequence_start"], business_id
        ))
    log_audit("UPDATE","BUSINESS",business_id,data["business_name"],"Business profile updated",business_id=business_id)


def list_clients():
    with get_connection() as conn:
        return [dict(r) for r in conn.execute(
            "SELECT * FROM clients WHERE business_id=? ORDER BY name COLLATE NOCASE",
            (_active_business_id(),)
        ).fetchall()]


def get_client(client_id):
    with get_connection() as conn:
        return row_to_dict(conn.execute(
            "SELECT * FROM clients WHERE id=? AND business_id=?",
            (client_id, _active_business_id())
        ).fetchone())


def save_client(data, client_id=None):
    bid=_active_business_id()
    with get_connection() as conn:
        if client_id:
            conn.execute("UPDATE clients SET name=?,gstin=?,address=?,state=?,state_code=? WHERE id=? AND business_id=?",
                         (data["name"],data["gstin"],data["address"],data["state"],data["state_code"],client_id,bid))
            saved_id=client_id; action="UPDATE"
        else:
            cur=conn.execute("INSERT INTO clients(name,gstin,address,state,state_code,business_id) VALUES(?,?,?,?,?,?) RETURNING id",
                             (data["name"],data["gstin"],data["address"],data["state"],data["state_code"],bid))
            saved_id=cur.fetchone()["id"]; action="CREATE"
    log_audit(action,"CLIENT",saved_id,data["name"],"Client saved",business_id=bid)
    return saved_id


def delete_client(client_id):
    bid = _active_business_id()
    with get_connection() as conn:
        used = conn.execute(
            "SELECT COUNT(*) c FROM invoices WHERE client_id=? AND business_id=?",
            (client_id, bid)
        ).fetchone()["c"]
        if used:
            raise ValueError("Client is already used in invoices and cannot be deleted.")
        conn.execute("DELETE FROM clients WHERE id=? AND business_id=?", (client_id, bid))
    log_audit("DELETE","CLIENT",client_id,"","Client deleted",business_id=bid)


def _insert_items(conn, invoice_id, items):
    for item in items:
        conn.execute("""
            INSERT INTO invoice_items(
                invoice_id,description,hsn_sac,quantity,unit,rate,discount_percent,
                gross_value,discount_amount,taxable_value,gst_rate,cgst_rate,sgst_rate,
                igst_rate,cgst_amount,sgst_amount,igst_amount,line_total
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        """, (
            invoice_id,item["description"],item["hsn_sac"],item["quantity"],item["unit"],
            item["rate"],item["discount_percent"],item["gross_value"],item["discount_amount"],
            item["taxable_value"],item["gst_rate"],item["cgst_rate"],item["sgst_rate"],
            item["igst_rate"],item["cgst_amount"],item["sgst_amount"],item["igst_amount"],
            item["line_total"]
        ))


def _upsert_item_masters(conn, items):
    bid=_active_business_id()
    for item in items:
        desc=item["description"].strip()
        row=conn.execute("SELECT id,item_code FROM item_master WHERE business_id=? AND LOWER(description)=LOWER(?)",(bid,desc)).fetchone()
        if row:
            conn.execute("UPDATE item_master SET hsn_sac=?,unit=?,default_rate=?,gst_rate=?,active=1,updated_at=CURRENT_TIMESTAMP WHERE id=?",
                         (item["hsn_sac"].strip(),item["unit"],item["rate"],item["gst_rate"],row["id"]))
        else:
            count=conn.execute("SELECT COUNT(*) c FROM item_master WHERE business_id=?",(bid,)).fetchone()["c"]
            code=f"ITM{int(count)+1:03d}"
            # Avoid collision if an item was deleted/reused.
            while conn.execute("SELECT 1 FROM item_master WHERE business_id=? AND item_code=?",(bid,code)).fetchone():
                count+=1; code=f"ITM{int(count)+1:03d}"
            conn.execute("INSERT INTO item_master(item_code,description,hsn_sac,unit,default_rate,gst_rate,active,business_id) VALUES(?,?,?,?,?,?,1,?)",
                         (code,desc,item["hsn_sac"].strip(),item["unit"],item["rate"],item["gst_rate"],bid))


def insert_invoice(invoice, items):
    bid = _active_business_id()
    with get_connection() as conn:
        client = conn.execute("SELECT id FROM clients WHERE id=? AND business_id=?", (invoice["client_id"], bid)).fetchone()
        if not client:
            raise ValueError("Selected client does not belong to the active business.")
        cur = conn.execute("""
            INSERT INTO invoices(
                invoice_no,invoice_date,client_id,place_of_supply_state,place_of_supply_code,
                tax_type,subtotal,discount_total,taxable_total,cgst_total,sgst_total,
                igst_total,grand_total,amount_in_words,notes,business_id,status,payment_status,amount_received,balance_due
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) RETURNING id
        """, (
            invoice["invoice_no"],invoice["invoice_date"],invoice["client_id"],
            invoice["place_of_supply_state"],invoice["place_of_supply_code"],invoice["tax_type"],
            invoice["subtotal"],invoice["discount_total"],invoice["taxable_total"],
            invoice["cgst_total"],invoice["sgst_total"],invoice["igst_total"],
            invoice["grand_total"],invoice["amount_in_words"],invoice["notes"],bid,
            invoice.get("status","ACTIVE"),invoice.get("payment_status","Unpaid"),
            float(invoice.get("amount_received",0) or 0),float(invoice.get("balance_due",invoice["grand_total"]) or 0)
        ))
        invoice_id = cur.fetchone()["id"]
        _insert_items(conn, invoice_id, items)
        _upsert_item_masters(conn, items)
    log_audit("CREATE","INVOICE",invoice_id,invoice["invoice_no"],"Invoice created",business_id=bid)
    return invoice_id


def update_invoice(invoice_id, invoice, items):
    bid = _active_business_id()
    with get_connection() as conn:
        existing = conn.execute(
            "SELECT invoice_no FROM invoices WHERE id=? AND business_id=?",
            (invoice_id,bid)
        ).fetchone()
        if not existing:
            raise ValueError("Invoice not found.")
        status_row=conn.execute("SELECT status FROM invoices WHERE id=? AND business_id=?",(invoice_id,bid)).fetchone()
        if status_row and status_row["status"] == "CANCELLED":
            raise ValueError("Cancelled invoices cannot be edited.")
        conn.execute("""
            UPDATE invoices SET invoice_date=?,client_id=?,place_of_supply_state=?,
            place_of_supply_code=?,tax_type=?,subtotal=?,discount_total=?,taxable_total=?,
            cgst_total=?,sgst_total=?,igst_total=?,grand_total=?,amount_in_words=?,notes=?
            WHERE id=? AND business_id=?
        """, (
            invoice["invoice_date"],invoice["client_id"],invoice["place_of_supply_state"],
            invoice["place_of_supply_code"],invoice["tax_type"],invoice["subtotal"],
            invoice["discount_total"],invoice["taxable_total"],invoice["cgst_total"],
            invoice["sgst_total"],invoice["igst_total"],invoice["grand_total"],
            invoice["amount_in_words"],invoice["notes"],invoice_id,bid
        ))
        conn.execute("DELETE FROM invoice_items WHERE invoice_id=?", (invoice_id,))
        _insert_items(conn,invoice_id,items)
        _upsert_item_masters(conn,items)
    log_audit("UPDATE","INVOICE",invoice_id,invoice["invoice_no"],"Invoice updated",business_id=bid)
    return invoice_id


def cancel_invoice(invoice_id, reason):
    bid=_active_business_id(); reason=(reason or "").strip(); uid=_current_user_id()
    if not reason: raise ValueError("Cancellation reason is required.")
    with get_connection() as conn:
        row=conn.execute("SELECT invoice_no,status FROM invoices WHERE id=? AND business_id=?",(invoice_id,bid)).fetchone()
        if not row: raise ValueError("Invoice not found.")
        if row["status"] == "CANCELLED": raise ValueError("Invoice is already cancelled.")
        conn.execute("UPDATE invoices SET status='CANCELLED',cancellation_reason=?,cancelled_at=CURRENT_TIMESTAMP,cancelled_by_user_id=? WHERE id=? AND business_id=?",(reason,uid,invoice_id,bid))
        no=row["invoice_no"]
    log_audit("CANCEL","INVOICE",invoice_id,no,reason,business_id=bid)
    return no


def update_invoice_payment(invoice_id, amount_received):
    bid=_active_business_id(); amount=float(amount_received or 0)
    with get_connection() as conn:
        row=conn.execute("SELECT invoice_no,grand_total,status FROM invoices WHERE id=? AND business_id=?",(invoice_id,bid)).fetchone()
        if not row: raise ValueError("Invoice not found.")
        if row["status"] == "CANCELLED": raise ValueError("Cancelled invoice cannot receive payment.")
        amount=max(0,min(amount,float(row["grand_total"])))
        balance=max(0,float(row["grand_total"])-amount)
        status="Paid" if balance < 0.005 else ("Partially Paid" if amount > 0 else "Unpaid")
        conn.execute("UPDATE invoices SET amount_received=?,balance_due=?,payment_status=? WHERE id=? AND business_id=?",(amount,balance,status,invoice_id,bid))
        no=row["invoice_no"]
    log_audit("PAYMENT","INVOICE",invoice_id,no,f"Amount received: {amount:.2f}",business_id=bid)
    return status,balance


def delete_invoice(invoice_id):
    bid = _active_business_id()
    with get_connection() as conn:
        row = conn.execute(
            "SELECT invoice_no FROM invoices WHERE id=? AND business_id=?",
            (invoice_id,bid)
        ).fetchone()
        if not row:
            raise ValueError("Invoice not found.")
        status=conn.execute("SELECT status FROM invoices WHERE id=? AND business_id=?",(invoice_id,bid)).fetchone()["status"]
        if status != "CANCELLED":
            raise ValueError("Invoice must be cancelled before permanent deletion.")
        conn.execute("DELETE FROM invoices WHERE id=? AND business_id=?", (invoice_id,bid))
        no=row["invoice_no"]
    log_audit("DELETE","INVOICE",invoice_id,no,"Cancelled invoice permanently deleted",business_id=bid)
    return no


def get_invoice(invoice_id):
    bid = _active_business_id()
    with get_connection() as conn:
        inv = conn.execute("""
            SELECT i.*,c.name client_name,c.gstin client_gstin,c.address client_address,
                   c.state client_state,c.state_code client_state_code
            FROM invoices i JOIN clients c ON c.id=i.client_id AND c.business_id=i.business_id
            WHERE i.id=? AND i.business_id=?
        """, (invoice_id,bid)).fetchone()
        if not inv:
            return None,[]
        items = conn.execute("SELECT * FROM invoice_items WHERE invoice_id=? ORDER BY id",(invoice_id,)).fetchall()
        return dict(inv),[dict(x) for x in items]


def list_invoices(start_date=None,end_date=None,client_id=None,search_text=None,include_cancelled=False):
    bid = _active_business_id()
    sql = """
        SELECT i.*,c.name client_name,c.gstin client_gstin,c.state client_state,c.state_code client_state_code
        FROM invoices i JOIN clients c ON c.id=i.client_id AND c.business_id=i.business_id
    """
    params, clauses = [], ["i.business_id=?"]
    params.append(bid)
    if not include_cancelled:
        clauses.append("i.status <> 'CANCELLED'")
    if start_date:
        clauses.append("i.invoice_date>=?"); params.append(start_date)
    if end_date:
        clauses.append("i.invoice_date<=?"); params.append(end_date)
    if client_id:
        clauses.append("i.client_id=?"); params.append(client_id)
    if search_text:
        clauses.append("(i.invoice_no LIKE ? OR c.name LIKE ? OR c.gstin LIKE ?)")
        term=f"%{search_text.strip()}%"
        params.extend([term,term,term])
    sql += " WHERE " + " AND ".join(clauses) + " ORDER BY i.invoice_date DESC,i.id DESC"
    with get_connection() as conn:
        return [dict(r) for r in conn.execute(sql,params).fetchall()]


def list_items(active_only=False):
    bid = _active_business_id()
    sql = "SELECT * FROM item_master WHERE business_id=?"
    params=[bid]
    if active_only:
        sql += " AND active=1"
    sql += " ORDER BY description COLLATE NOCASE"
    with get_connection() as conn:
        return [dict(r) for r in conn.execute(sql,params).fetchall()]


def get_item(item_id):
    with get_connection() as conn:
        return row_to_dict(conn.execute(
            "SELECT * FROM item_master WHERE id=? AND business_id=?",
            (item_id,_active_business_id())
        ).fetchone())


def save_item(data,item_id=None):
    bid=_active_business_id(); code=(data.get("item_code") or "").strip()
    with get_connection() as conn:
        if item_id:
            if not code:
                code=conn.execute("SELECT item_code FROM item_master WHERE id=? AND business_id=?",(item_id,bid)).fetchone()["item_code"] or ""
            conn.execute("UPDATE item_master SET item_code=?,description=?,hsn_sac=?,unit=?,default_rate=?,gst_rate=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND business_id=?",
                         (code,data["description"],data["hsn_sac"],data["unit"],data["default_rate"],data["gst_rate"],int(data.get("active",1)),item_id,bid))
            saved_id=item_id; action="UPDATE"
        else:
            if not code:
                count=conn.execute("SELECT COUNT(*) c FROM item_master WHERE business_id=?",(bid,)).fetchone()["c"]
                code=f"ITM{int(count)+1:03d}"
            if conn.backend=="postgresql":
                cur=conn.execute("INSERT INTO item_master(item_code,description,hsn_sac,unit,default_rate,gst_rate,active,business_id) VALUES(?,?,?,?,?,?,?,?) RETURNING id",
                                 (code,data["description"],data["hsn_sac"],data["unit"],data["default_rate"],data["gst_rate"],int(data.get("active",1)),bid))
                saved_id=cur.fetchone()["id"]
            else:
                cur=conn.execute("INSERT INTO item_master(item_code,description,hsn_sac,unit,default_rate,gst_rate,active,business_id) VALUES(?,?,?,?,?,?,?,?)",
                                 (code,data["description"],data["hsn_sac"],data["unit"],data["default_rate"],data["gst_rate"],int(data.get("active",1)),bid))
                saved_id=cur.lastrowid
            action="CREATE"
    log_audit(action,"ITEM",saved_id,code,data["description"],business_id=bid)
    return saved_id


def delete_item(item_id):
    bid=_active_business_id()
    with get_connection() as conn:
        row=conn.execute("SELECT item_code,description FROM item_master WHERE id=? AND business_id=?",(item_id,bid)).fetchone()
        if not row: raise ValueError("Item not found.")
        used=conn.execute("SELECT COUNT(*) c FROM invoice_items ii JOIN invoices i ON i.id=ii.invoice_id WHERE ii.description=? AND i.business_id=?",(row["description"],bid)).fetchone()["c"]
        if used: raise ValueError("Item has been used in invoices and cannot be deleted. Mark it inactive instead.")
        conn.execute("DELETE FROM item_master WHERE id=? AND business_id=?",(item_id,bid))
        code=row["item_code"]; desc=row["description"]
    log_audit("DELETE","ITEM",item_id,code,desc,business_id=bid)


def report_rows(start_date,end_date):
    bid=_active_business_id()
    with get_connection() as conn:
        return [dict(r) for r in conn.execute("""
            SELECT i.id invoice_id,i.invoice_no,i.invoice_date,i.place_of_supply_state,
                   i.place_of_supply_code,i.tax_type,i.grand_total invoice_value,
                   c.name client_name,c.gstin receiver_gstin,it.description,it.hsn_sac,
                   it.quantity,it.unit,it.gst_rate,it.gross_value,it.taxable_value,
                   it.cgst_amount,it.sgst_amount,it.igst_amount
            FROM invoices i
            JOIN clients c ON c.id=i.client_id AND c.business_id=i.business_id
            JOIN invoice_items it ON it.invoice_id=i.id
            WHERE i.business_id=? AND i.status <> 'CANCELLED' AND i.invoice_date BETWEEN ? AND ?
            ORDER BY i.invoice_date,i.id,it.id
        """,(bid,start_date,end_date)).fetchall()]


def find_client_for_import(name,gstin=""):
    bid=_active_business_id()
    name=(name or "").strip()
    gstin=(gstin or "").strip().upper()
    with get_connection() as conn:
        if gstin:
            row=conn.execute(
                "SELECT * FROM clients WHERE business_id=? AND UPPER(TRIM(gstin))=? LIMIT 1",
                (bid,gstin)
            ).fetchone()
            if row: return dict(row)
        row=conn.execute(
            "SELECT * FROM clients WHERE business_id=? AND LOWER(TRIM(name))=LOWER(?) LIMIT 1",
            (bid,name)
        ).fetchone()
        return dict(row) if row else None


def invoice_number_exists(invoice_no):
    with get_connection() as conn:
        return bool(conn.execute(
            "SELECT 1 FROM invoices WHERE business_id=? AND invoice_no=? LIMIT 1",
            (_active_business_id(),invoice_no)
        ).fetchone())


def get_user_by_username(username):
    with get_connection() as conn:
        row=conn.execute(
            "SELECT * FROM app_users WHERE LOWER(username)=LOWER(?) LIMIT 1",
            ((username or "").strip(),)
        ).fetchone()
        return dict(row) if row else None


def count_users():
    with get_connection() as conn:
        return int(conn.execute("SELECT COUNT(*) c FROM app_users").fetchone()["c"])


def create_user(username,password_hash,role="User"):
    username=(username or "").strip()
    if not username: raise ValueError("Username is required.")
    with get_connection() as conn:
        if conn.backend=="postgresql":
            cur=conn.execute("INSERT INTO app_users(username,password_hash,role,active) VALUES(?,?,?,1) RETURNING id",(username,password_hash,role))
            user_id=cur.fetchone()["id"]
        else:
            cur=conn.execute("INSERT INTO app_users(username,password_hash,role,active) VALUES(?,?,?,1)",(username,password_hash,role))
            user_id=cur.lastrowid
    log_audit("CREATE","USER",user_id,username,f"Role: {role}",user_id=_current_user_id(),business_id=None)
    return user_id


def delete_user(user_id):
    user_id=int(user_id)
    if user_id==_current_user_id(): raise ValueError("You cannot delete the account currently signed in.")
    with get_connection() as conn:
        row=conn.execute("SELECT username FROM app_users WHERE id=?",(user_id,)).fetchone()
        if not row: raise ValueError("User not found.")
        owned=conn.execute("SELECT COUNT(*) c FROM businesses WHERE created_by_user_id=?",(user_id,)).fetchone()["c"]
        if owned: raise ValueError("This user has created a Business. Deactivate the user instead of deleting the account.")
        conn.execute("DELETE FROM user_business_access WHERE user_id=?",(user_id,))
        conn.execute("DELETE FROM app_users WHERE id=?",(user_id,))
        username=row["username"]
    log_audit("DELETE","USER",user_id,username,"User deleted",user_id=_current_user_id(),business_id=None)


def list_users():
    with get_connection() as conn:
        return [dict(r) for r in conn.execute(
            "SELECT id,username,role,active,created_at,updated_at FROM app_users ORDER BY username COLLATE NOCASE"
        ).fetchall()]


def get_user_business_access(user_id):
    with get_connection() as conn:
        rows=conn.execute("""
            SELECT b.*
            FROM businesses b JOIN user_business_access uba ON uba.business_id=b.id
            WHERE uba.user_id=? AND b.active=1 ORDER BY b.business_name COLLATE NOCASE
        """,(user_id,)).fetchall()
        return [dict(r) for r in rows]


def set_user_business_access(user_id,business_ids):
    business_ids={int(x) for x in business_ids}
    with get_connection() as conn:
        conn.execute("DELETE FROM user_business_access WHERE user_id=?",(user_id,))
        for bid in business_ids:
            conn.execute("INSERT INTO user_business_access(user_id,business_id) VALUES(?,?)",(user_id,bid))


def add_user_business_access(user_id,business_id):
    with get_connection() as conn:
        if conn.backend == "postgresql":
            conn.execute(
                "INSERT INTO user_business_access(user_id,business_id) VALUES(?,?) ON CONFLICT DO NOTHING",
                (user_id,business_id)
            )
        else:
            conn.execute(
                "INSERT OR IGNORE INTO user_business_access(user_id,business_id) VALUES(?,?)",
                (user_id,business_id)
            )


def update_user_role(user_id,role):
    with get_connection() as conn:
        conn.execute("UPDATE app_users SET role=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",(role,user_id))
    log_audit("UPDATE","USER",user_id,"",f"Role: {role}",user_id=_current_user_id(),business_id=None)


def update_user_password(user_id,password_hash):
    with get_connection() as conn:
        conn.execute("UPDATE app_users SET password_hash=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",(password_hash,user_id))
    log_audit("PASSWORD","USER",user_id,"","Password reset",user_id=_current_user_id(),business_id=None)


def set_user_active(user_id,active):
    with get_connection() as conn:
        conn.execute("UPDATE app_users SET active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",(1 if active else 0,user_id))
    log_audit("ACTIVATE" if active else "DEACTIVATE","USER",user_id,"","User status changed",user_id=_current_user_id(),business_id=None)


def update_login_failure(user_id,failed_count,locked_until=""):
    with get_connection() as conn:
        conn.execute(
            "UPDATE app_users SET failed_login_count=?,locked_until=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",
            (int(failed_count),locked_until or "",user_id)
        )


def reset_login_failure(user_id):
    with get_connection() as conn:
        conn.execute(
            "UPDATE app_users SET failed_login_count=0,locked_until='',last_login_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?",
            (user_id,)
        )


def get_user_security_state(user_id):
    with get_connection() as conn:
        row=conn.execute(
            "SELECT failed_login_count,locked_until,last_login_at FROM app_users WHERE id=?",(user_id,)
        ).fetchone()
        return dict(row) if row else None
